"""empty message

Revision ID: 009b91167d0a
Revises: 9add9c12ed9d
Create Date: 2021-09-06 19:26:18.651494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009b91167d0a'
down_revision = '9add9c12ed9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('pin', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pin')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
