"""empty message

Revision ID: 521077060e37
Revises: eca0ee9db3e5
Create Date: 2021-11-10 21:29:07.838867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '521077060e37'
down_revision = 'eca0ee9db3e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('userID', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'userID')
    # ### end Alembic commands ###
