"""empty message

Revision ID: 7e8c99a10be5
Revises: bb12ba205930
Create Date: 2021-10-16 11:30:50.364634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e8c99a10be5'
down_revision = 'bb12ba205930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('ref_no', sa.String(length=20), nullable=False),
    sa.Column('id_no', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('deposit', sa.Integer(), nullable=True),
    sa.Column('withdrawal', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('ref_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
