"""empty message

Revision ID: b5c5c09ce7ce
Revises: e79195374e77
Create Date: 2021-11-03 22:54:50.999921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c5c09ce7ce'
down_revision = 'e79195374e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deposits',
    sa.Column('ref_no', sa.String(length=15), nullable=False),
    sa.Column('id_no', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('ref_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deposits')
    # ### end Alembic commands ###
