"""empty message

Revision ID: e79195374e77
Revises: 7e8c99a10be5
Create Date: 2021-11-03 08:43:37.084896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79195374e77'
down_revision = '7e8c99a10be5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notification', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification')
    # ### end Alembic commands ###
