"""empty message

Revision ID: eca0ee9db3e5
Revises: b5c5c09ce7ce
Create Date: 2021-11-07 18:50:30.018046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eca0ee9db3e5'
down_revision = 'b5c5c09ce7ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inactive_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inactive_users')
    # ### end Alembic commands ###
